services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongodb/data:/tmp/data   # Aquí mantienes el volumen para los datos
    command: >
      bash -c "echo '########### Loading data to Mongo DB ###########' &&
               mongoimport --jsonArray --db practica-database --collection users --file /tmp/data/users.json &&
               docker-entrypoint.sh mongod"  # Ejecuta el comando mongoimport y luego inicia MongoDB
    networks:
      - node-network

  node-app:
    build: .
    image: node-app
    container_name: node-app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    command: ["npm", "start"]
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
