version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongodb/create-db.js:/docker-entrypoint-initdb.d/create-db.js:ro
      - ./init-mongodb/data:/tmp/data
    networks:
      - node-network
  
  node-app:
    build: .
    image: node-app
    container_name: node-app
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    command: ["npm", "start"]
    networks:
      - node-network

volumes:
  mongodb_data:

networks:
  node-network:
    driver: bridge